threads = 20
verbose = false
retries = 5
subdomains = true
parameters = false
providers = ["wayback","commoncrawl","otx","urlscan"]
blacklist = ["ttf","woff","svg","png","jpg","gif","ico","css","pdf","mp4","mp3"]
json = false

[urlscan]
  apikey = ""

[filters]
  from = ""
  to = ""
  matchstatuscodes = []
  matchmimetypes = []
  filterstatuscodes = []
  filtermimetypes = ["image/png","image/jpg","image/svg+xml","image/gif"]
